name: Cowfire
description: >
  A Demo App which does almost nothing of any practical value.
version: 0.0.1-rancher1
category: demo
maintainer: Keerthiraja <sjkeerthi@gmail.com>
license: Apache2
projectURL: https://github.com/sjkeerthi/Cowfire
